DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS participants;
ALTER TABLE IF EXISTS meetings DROP CONSTRAINT IF EXISTS fk_confirmed_slot;
DROP TABLE IF EXISTS time_slots;
DROP TABLE IF EXISTS meetings;
DROP TABLE IF EXISTS users;
