apiVersion: 1

# Tell Grafana to forward alerts to the external Alertmanager
# instead of using the built-in one
contactPoints:
  - orgId: 1
    name: alertmanager-external
    receivers:
      - uid: alertmanager-external
        type: prometheus-alertmanager
        settings:
          url: http://localhost:9093
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: alertmanager-external
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
